name : End-to-end-test
on: push
jobs :
  cypress-run:
    runs-on : ubuntu-22.04
    steps :
      - name : checkout
        users : actions/checkout@v3
      - name : Cypress run
        users : cypress-io/github-action@v5